#!/usr/bin/env python3
"""연운(烟雨江湖) 85레벨 가이드 한글 번역 스크립트"""
import zipfile, os, re
import xml.etree.ElementTree as ET

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(SCRIPT_DIR, '85레벨 연운 아이템 조율 및 방향성 가이드.xlsx')
OUTPUT = os.path.join(SCRIPT_DIR, '85레벨 연운 아이템 조율 및 방향성 가이드_한글.xlsx')

# ============================================================
# 시트명 번역
# ============================================================
SHEET_NAME_MAP = {
    'Nameless 85': '무명 85',
    'Jade 85': '옥소 85',
    'Umber85': '갈의 85',
    'Twinblades 85': '쌍검 85',
    'Mo Blade85': '막도 85',
    'Healer 85': '힐러 85',
    '各流派历史等级毕业配置': '유파별 졸업세팅',
    '伤害公式': '데미지 공식',
    '各种机制说明': '메커니즘 설명',
    '技能表': '스킬표',
    'Buff表': '버프표',
    '各等级模板': '레벨별 템플릿',
    '纯陌1分钟桩': '순수막도 1분DPS',
    '箫蛤2轮': '소합 2라운드',
    '大风车': '대풍차',
    '双刀鼠鼠（废弃）': '쌍도(폐기)',
    '61级装备词条品阶数值对应关系一览表': '61렙 옵션등급표',
    '71级装备词条品阶数值对应关系一览表': '71렙 옵션등급표',
    '更新日志&赞助名单': '업데이트로그',
    '倍率测算器': '배율계산기',
    'PVP': 'PVP',
}

# ============================================================
# 게임 용어 사전: (원문, 한글(영문)) 
# 긴 용어부터 자동 정렬하여 부분 매칭 방지
# ============================================================
TERM_DICT_RAW = [
    # ===== 긴 복합 구문 (먼저 번역) =====
    ('词条收益计算自动化区，分割线以下的内容一般不用改', '옵션수익 자동계산구간, 구분선 아래는 수정불필요'),
    ('下载之后可以编辑，在D列填你的白字面板、定音、增伤，填之前把DIY里面的各词条清零',
     '다운로드 후 편집가능. D열에 백자패널/정음/증상 입력. 입력 전 DIY옵션을 모두 0으로 초기화'),
    ('根据左边面板的词条动态提升', '좌측 패널 옵션 기반 동적 향상'),
    ('After downloading, you can edit it. Fill in your white text panel, attune, and damage increase in column D. Before filling, clear all affixes in the DIY section to zero.',
     '다운로드 후 편집가능. D열에 백자패널/정음/증상 입력. 입력 전 DIY옵션을 모두 0으로 초기화'),
    ('Dynamic enhancement based on affixes in the left panel', '좌측 패널 옵션 기반 동적 향상'),
    ('好久没玩了，不太准（高延迟地区）', '오래 안해서 부정확 (고핑지역)'),
    ('豆沙包轴（高延迟地区）', '두사포 로테이션(고핑지역)'),
    ('傻白打桩（低延迟地区）', '단순백도 딜측정(저핑지역)'),
    # ===== 영문 속성명 =====
    ('Criti + Affinity ', '회심+회의(Criti+Affinity)'),
    ('Translation->', '번역→'),
    ('Translation', '번역(Translation)'),
    ('Attribute Type', '속성유형(Attribute Type)'),
    ('85 Basic', '85기본(85 Basic)'),
    ('Your pannel', '내 패널(Your Panel)'),
    ('Graduation Degree', '졸업도(Graduation Degree)'),
    ('Min atk', '최소외공(Min ATK)'),
    ('Max atk', '최대외공(Max ATK)'),
    ('Min attri.', '최소속성공(Min Attri.)'),
    ('Max attri.', '최대속성공(Max Attri.)'),
    ('Min other attri.', '최소외속공(Min Other Attri.)'),
    ('Max other attri.', '최대외속공(Max Other Attri.)'),
    ('All weapon boost', '전무기증상(All Weapon Boost)'),
    ('Mystic skill boost', '최고기술증상(Mystic Skill Boost)'),
    ('Boss boost', '수령증상(Boss Boost)'),
    ('Phy Penetration', '외공관통(Phys Penetration)'),
    ('Physical DMG Bonus', '외상증가(Physical DMG Bonus)'),
    ('Attri. Penetration', '속성관통(Attri. Penetration)'),
    ('Attri. DMG Bonus', '속성피해증가(Attri. DMG Bonus)'),
    ('Charge skill attune', '차지스킬 정음(Charge Skill Attune)'),
    ('charge skill attune', '차지 정음(Charge Skill Attune)'),
    ('Optional Parameters', '선택 파라미터(Optional Parameters)'),
    ('Ratio of breaking point', '단석비율(Breaking Point Ratio)'),
    ('Ratio of exhaustion', '기갈비율(Exhaustion Ratio)'),
    ('Unfading Flower attune', '무인기 정음(Unfading Flower Attune)'),
    ('heavy skill attune', '중격 정음(Heavy Skill Attune)'),
    ('blood attune', '유혈 정음(Blood Attune)'),
    ('rat attune', '쥐 정음(Rat Attune)'),
    ('Sword boost', '검증상(Sword Boost)'),
    ('sword boost', '검증상(Sword Boost)'),
    ('spear boost', '창증상(Spear Boost)'),
    ('rope boost', '승표증상(Rope Boost)'),
    ('Umbrella boost', '산증상(Umbrella Boost)'),
    ('MoBlade boost', '막도증상(MoBlade Boost)'),
    ('Player boost', '플레이어증상(Player Boost)'),
    ('fan boost', '부채증량(Fan Boost)'),
    ('weapon boost', '무기증상(Weapon Boost)'),
    ('Dir. Criti', '직접회심(Dir. Criti)'),
    ('Dir. Affinity', '직접회의(Dir. Affinity)'),
    ('Criti DMG', '회심피해(Criti DMG)'),
    ('Affinity DMG', '회의피해(Affinity DMG)'),
    ('Criti', '회심(Criti)'),
    ('Precision', '정확(Precision)'),
    ('Affinity', '회의(Affinity)'),
    ('Power', '근(Power)'),
    ('Agility', '민(Agility)'),
    ('Momentum', '세(Momentum)'),
    ('Inner way', '내공(Inner Way)'),
    ('morale chant', '역수가(Morale Chant)'),
    ('envigorated warrior', '징인귀(Envigorated Warrior)'),
    ('bitter season', '소한연년(Bitter Season)'),
    ('Jadeware', '옥두(Jadeware)'),
    ('atk food', '공격음식(ATK Food)'),
    ('hawking', '비준(Hawking)'),
    # ===== 영문 버프 조합 (풀 오버라이드) =====
    ('morale chant, mountain\'s might, Sword Morph, battle anthem',
     '역수가, 산의위엄, 검변, 전가(Morale Chant, Mountain\'s Might, Sword Morph, Battle Anthem)'),
    ('Blossom Barrage, morale chant, Breaking Point, envigorated warrior',
     '꽃난사, 역수가, 단석, 징인귀(Blossom Barrage, Morale Chant, Breaking Point, Envigorated Warrior)'),
    ('morale chant, Crisscrossing Swords, wolfchaser\'s art, insightful strike',
     '역수가, 종횡검, 낭두술, 통찰타격(Morale Chant, Crisscrossing Swords, Wolfchaser\'s Art, Insightful Strike)'),
    ('fivefold bleed, echoes of oblivion, vendetta, morale chant',
     '5중유혈, 망천의울림, 복수, 역수가(Fivefold Bleed, Echoes of Oblivion, Vendetta, Morale Chant)'),
    ('morale chant, battle anthem, golden path, adaptive steel',
     '역수가, 전가, 금도, 변강(Morale Chant, Battle Anthem, Golden Path, Adaptive Steel)'),
    ('Mending Loom,royal remedy,  morale chant, silkbind',
     '직조, 왕실치료, 역수가, 견사결(Mending Loom, Royal Remedy, Morale Chant, Silkbind)'),
    # ===== 중문 - 복합 용어 (긴 것 먼저) =====
    ('外攻伤害加深', '외공피해심화(Phys DMG Deepen)'),
    ('本系伤害加深', '본계피해심화(Attri DMG Deepen)'),
    ('外攻百分比放大', '외공%증폭(ATK% Amplify)'),
    ('武学技增伤百分比', '무학기증상%(Martial Skill DMG%)'),
    ('武器增伤百分比', '무기증상%(Weapon DMG%)'),
    ('全武器增伤百分比', '전무기증상%(All Weapon DMG%)'),
    ('技能增伤（易武、跳劈、突进、处决）百分比', '스킬증상(역무/점벽/돌진/처결)%'),
    ('技能增伤（易武、跳劈、突进）百分比', '스킬증상(역무/점벽/돌진)%'),
    ('外攻百分比', '외공%(ATK%)'),
    ('最小外攻攻击', '최소외공(Min ATK)'),
    ('最大外功攻击', '최대외공(Max ATK)'),
    ('最小属性攻击', '최소속성공(Min Attri ATK)'),
    ('最大属性攻击', '최대속성공(Max Attri ATK)'),
    ('会心率百分比', '회심률%(Crit Rate%)'),
    ('会意率百分比', '회의률%(Affinity Rate%)'),
    ('精准率百分比', '정확률%(Precision%)'),
    ('气血最大值', '최대기혈(Max HP)'),
    ('词条优先级', '옵션우선순위(Affix Priority)'),
    ('词条领先度', '옵션선행도(Affix Lead)'),
    ('词条提升', '옵션향상(Affix Boost)'),
    ('伤害期望', '피해기대치(DMG Expected)'),
    ('技能总伤害', '스킬총피해(Total Skill DMG)'),
    ('外攻伤害', '외공피해(Phys DMG)'),
    ('本系伤害', '본계피해(Attri DMG)'),
    ('固伤伤害', '고정피해량(Fixed DMG)'),
    ('外攻穿透', '외공관통(Phys Penetration)'),
    ('外伤增加', '외상증가(Phys DMG Bonus)'),
    ('本系穿透', '본계관통(Attri Penetration)'),
    ('外攻防御', '외공방어(Phys DEF)'),
    ('外攻抗性', '외공저항(Phys Resist)'),
    ('判定抗性', '판정저항(Judgment Resist)'),
    ('属性穿透', '속성관통(Attri Penetration)'),
    ('独立乘区', '독립승구(Indep Multi)'),
    ('独立结算区', '독립정산구(Indep Settle Zone)'),
    ('独立结算', '독립정산(Indep Settle)'),
    ('独立增伤', '독립증상(Indep DMG Boost)'),
    ('伤害加深区', '피해심화구(DMG Deepen Zone)'),
    ('伤害加深', '피해심화(DMG Deepen)'),
    ('增伤区A', '증상구A(DMG Boost Zone A)'),
    ('增伤区', '증상구(DMG Boost Zone)'),
    ('通用增伤区', '범용증상구(General DMG Zone)'),
    ('通用增伤', '범용증상(General DMG Boost)'),
    ('蓄力增伤', '차지증상(Charge DMG Boost)'),
    ('武器增伤', '무기증상(Weapon DMG Boost)'),
    ('首领增伤', '수령증상(Boss DMG Boost)'),
    ('蹊跷首领增伤', '기교수령증상(Trick Boss DMG)'),
    ('蹊跷增伤', '기교증상(Trick DMG Boost)'),
    ('奇术增伤', '기술증상(Mystic DMG Boost)'),
    ('武学增伤', '무학증상(Martial DMG Boost)'),
    ('轻击重击增伤', '경/중격증상(Light/Heavy DMG Boost)'),
    ('弹道增伤', '탄도증상(Projectile DMG Boost)'),
    ('处决增伤', '처결증상(Execute DMG Boost)'),
    ('连击增伤', '연격증상(Combo DMG Boost)'),
    ('单体增伤', '단일증상(Single DMG Boost)'),
    ('单爆增伤', '단폭증상(Single Burst DMG)'),
    ('横刀增伤', '횡도증상(Cross Blade DMG)'),
    ('天赋增伤', '천부증상(Talent DMG Boost)'),
    ('共鸣增伤', '공명증상(Resonance DMG)'),
    ('吹箫小人增伤', '취소소인증상(Flute Minion DMG)'),
    ('吹箫蓄力增伤', '취소차지증상(Flute Charge DMG)'),
    ('气血增伤', '기혈증상(HP DMG Boost)'),
    ('耐力增伤', '내력증상(Stamina DMG Boost)'),
    ('血爆增伤', '혈폭증상(Blood Burst DMG)'),
    ('持续伤增伤', '지속피해증상(DoT DMG Boost)'),
    ('枪Q增伤', '창Q증상(Spear Q DMG)'),
    ('奶伞增伤', '힐산증상(Heal Umbrella DMG)'),
    ('4选1增伤', '4선택1증상(Choose 1 of 4 DMG)'),
    ('4选1减伤', '4선택1감상(Choose 1 of 4 Reduce)'),
    ('增伤词条', '증상옵션(DMG Boost Affix)'),
    ('四伤占比', '4피해비율(4 DMG Ratio)'),
    ('会心伤害', '회심피해(Crit DMG)'),
    ('会意伤害', '회의피해(Affinity DMG)'),
    ('原始伤害', '원시피해(Raw DMG)'),
    ('造成伤害', '적용피해(Final DMG)'),
    ('参考DPS', '참고DPS'),
    ('参考加血', '참고힐량(Ref HPS)'),
    ('加权DPS', '가중DPS(Weighted DPS)'),
    ('0词条提升', '0옵션 향상'),
    ('0词条参考DPS', '0옵션 참고DPS'),
    ('词条DIY', '옵션DIY(Affix DIY)'),
    ('可选参数', '선택파라미터(Optional Params)'),
    # ===== 중문 - 속성/스탯 =====
    ('属性类型', '속성유형(Attribute Type)'),
    ('属性倍率', '속성배율(Attri Ratio)'),
    ('本属倍率', '본속배율(Main Attri Ratio)'),
    ('外攻倍率', '외공배율(ATK Ratio)'),
    ('属性', '속성(Attribute)'),
    ('最小外攻', '최소외공(Min ATK)'),
    ('最大外攻', '최대외공(Max ATK)'),
    ('精准率', '정확률(Precision)'),
    ('会心率', '회심률(Crit Rate)'),
    ('直接会心', '직접회심(Dir Crit)'),
    ('直接会意', '직접회의(Dir Affinity)'),
    ('会意率', '회의률(Affinity Rate)'),
    ('会心抵抗', '회심저항(Crit Resist)'),
    ('会意抵抗', '회의저항(Affinity Resist)'),
    ('会意伤', '회의피해(Affinity DMG)'),
    ('精准', '정확(Precision)'),
    ('会伤', '회심피해(Crit DMG)'),
    ('会心', '회심(Crit)'),
    ('会意', '회의(Affinity)'),
    ('最小值', '최소값(Min)'),
    ('最大值', '최대값(Max)'),
    ('固伤', '고정피해(Fixed DMG)'),
    ('增伤', '증상(DMG Boost)'),
    ('减伤', '감상(DMG Reduce)'),
    ('白字', '백자(White Text)'),
    ('擦伤', '찰상(Graze)'),
    ('穿透', '관통(Penetration)'),
    ('加深', '심화(Deepen)'),
    ('外攻', '외공(Phys ATK)'),
    ('本系', '본계(Main Elem)'),
    ('外系', '외계(Other Elem)'),
    ('本属', '본속(Main Attri)'),
    ('大攻', '대공(Max ATK)'),
    ('小攻', '소공(Min ATK)'),
    ('本小', '본소(Main Min)'),
    ('本大', '본대(Main Max)'),
    ('劲', '근(Power)'),
    ('敏', '민(Agility)'),
    ('势', '세(Momentum)'),
    ('防御', '방어(Defense)'),
    ('防', '방(DEF)'),
    ('外穿', '외관통(Phys Pen)'),
    ('本穿', '본관통(Main Pen)'),
    ('外增', '외증(Phys Boost)'),
    ('属穿', '속관통(Attri Pen)'),
    ('外抗', '외저항(Phys Resist)'),
    ('属抗', '속저항(Attri Resist)'),
    ('单属抗', '단속저항(Single Attri Resist)'),
    ('属攻', '속공(Attri ATK)'),
    ('裂穿', '열관통(Crack Pen)'),
    ('全穿', '전관통(All Pen)'),
    # ===== 무기/유파 =====
    ('无名剑枪', '무명검창(Nameless)'),
    ('无名剑', '무명검(Nameless Sword)'),
    ('无名枪', '무명창(Nameless Spear)'),
    ('九剑', '구검(Nine Sword)'),
    ('九枪', '구창(Nine Spear)'),
    ('九伞', '구산(Nine Umbrella)'),
    ('嗟夫', '차부(JieFu)'),
    ('八枪', '팔창(Eight Spear)'),
    ('青扇', '청선(Blue Fan)'),
    ('粟子', '속자(Chestnut)'),
    ('陌刀', '막도(Mo Blade)'),
    ('山河', '산하(Mountain River)'),
    ('双刀', '쌍도(Twin Blade)'),
    ('鼠鼠', '쥐쥐(Rat)'),
    ('白刀', '백도(White Blade)'),
    ('红刀', '홍도(Red Blade)'),
    ('奶伞', '힐산(Heal Umbrella)'),
    ('奶扇', '힐부채(Heal Fan)'),
    ('横刀', '횡도(Cross Blade)'),
    ('无名', '무명(Nameless)'),
    ('双剑', '쌍검(Twin Sword)'),
    ('飞天伞', '비천산(Flying Umbrella)'),
    ('纯奶', '순힐(Pure Heal)'),
    # ===== 심법(Mind Method) =====
    ('易水歌', '역수가(Yishui Song)'),
    ('威猛歌', '위맹가(Might Song)'),
    ('威猛', '위맹(Might)'),
    ('断石', '단석(Stone Break)'),
    ('断岳', '단악(Mountain Cut)'),
    ('征人', '징인(Warrior)'),
    ('狼头', '낭두(Wolf Head)'),
    ('纵横', '종횡(Cross)'),
    ('泥鱼', '이어(Mudfish)'),
    ('凝神章', '응신장(Focus Seal)'),
    ('飞隼', '비준(Falcon)'),
    ('浣花', '환화(Wash Flower)'),
    ('玉斗', '옥두(Jade Cup)'),
    ('时雨', '시우(Timely Rain)'),
    ('千山', '천산(Thousand Mt)'),
    ('极乐', '극락(Paradise)'),
    ('天工', '천공(Heaven Work)'),
    ('抗造', '항조(Resilience)'),
    ('牵丝', '견사(Silk Thread)'),
    ('君臣', '군신(Lord Minister)'),
    ('杏花', '행화(Apricot)'),
    ('连星', '연성(Chain Star)'),
    ('岳山', '악산(Mountain Peak)'),
    ('所恨年年', '소한연년(Bitter Years)'),
    ('忘川', '망천(Oblivion River)'),
    ('千营', '천영(Thousand Camp)'),
    ('唐人', '당인(Tang People)'),
    ('行舟', '행주(Sailing)'),
    ('霜天', '상천(Frost Sky)'),
    ('铁衣', '철의(Iron Armor)'),
    ('开山', '개산(Mt Opener)'),
    ('明晦', '명회(Light Dark)'),
    ('孤忠', '고충(Lone Loyalty)'),
    ('涌泉', '용천(Spring)'),
    ('江流', '강류(River Flow)'),
    ('滴水', '적수(Drip)'),
    ('胆寒', '담한(Fear)'),
    ('惧刃', '구인(Blade Fear)'),
    ('穿喉', '천후(Throat Pierce)'),
    ('烟柳套', '연류세트(Smoke Willow Set)'),
    ('存煞帖', '존살첩(Evil Post)'),
    ('醉梦游春', '취몽유춘(Drunken Spring)'),
    # ===== 전투 메커니즘 =====
    ('词条', '옵션(Affix)'),
    ('轴长', '로테이션길이(Rotation Len)'),
    ('轴', '로테(Rotation)'),
    ('技能', '스킬(Skill)'),
    ('次数', '횟수(Count)'),
    ('占比', '비율(Ratio)'),
    ('加成', '가성(Bonus)'),
    ('定音', '정음(Attune)'),
    ('武器', '무기(Weapon)'),
    ('装备', '장비(Equipment)'),
    ('心法', '심법(Mind Method)'),
    ('天赋', '천부(Talent)'),
    ('蓄力', '차지(Charge)'),
    ('卸势', '허세(Unload)'),
    ('骑龙', '기룡(Ride Dragon)'),
    ('轮回', '윤회(Reincarnation)'),
    ('合计', '합계(Total)'),
    ('气竭', '기갈(Exhaustion)'),
    ('赛季', '시즌(Season)'),
    ('耐力', '내력(Stamina)'),
    ('真气', '진기(Chi)'),
    ('精元', '정원(Essence)'),
    ('奇术', '기술(Mystic)'),
    ('武学', '무학(Martial Art)'),
    ('流派', '유파(School)'),
    ('倍率', '배율(Multiplier)'),
    ('面板', '패널(Panel)'),
    ('基础', '기본(Basic)'),
    ('备注', '비고(Note)'),
    ('版本', '버전(Version)'),
    ('时间', '시간(Time)'),
    ('怪物', '몬스터(Monster)'),
    ('首领', '수령(Boss)'),
    ('副本', '던전(Dungeon)'),
    ('食物', '음식(Food)'),
    ('毕业度', '졸업도(Grad Degree)'),
    ('乘区', '승구(Multi Zone)'),
    ('独立区', '독립구(Indep Zone)'),
    ('减伤区', '감상구(Reduce Zone)'),
    ('穿透区', '관통구(Pen Zone)'),
    ('会心区', '회심구(Crit Zone)'),
    ('会意区', '회의구(Affinity Zone)'),
    ('定音区', '정음구(Attune Zone)'),
    ('独立', '독립(Independent)'),
    ('加成类型', '가성유형(Bonus Type)'),
    ('版本数据（级）', '버전데이터(레벨)'),
    # ===== 스킬/콤보 =====
    ('轻击', '경격(Light ATK)'),
    ('重击', '중격(Heavy ATK)'),
    ('派生', '파생(Follow-up)'),
    ('追击', '추격(Chase)'),
    ('吹箫', '취소(Flute)'),
    ('迷踪步', '미종보(Phantom Step)'),
    ('电钻', '전찬(Drill)'),
    ('十字', '십자(Cross)'),
    ('流星', '유성(Meteor)'),
    ('打拳', '타권(Punch)'),
    ('喷火', '분화(Fire Breath)'),
    ('爆燃', '폭연(Combustion)'),
    ('流血', '유혈(Bleed)'),
    ('血爆', '혈폭(Blood Burst)'),
    ('破阵', '파진(Formation Break)'),
    ('催鼓', '최고(Drum)'),
    ('防反', '방반(Parry)'),
    ('飞鸿', '비홍(Flying Swan)'),
    ('踏雪', '답설(Snow Step)'),
    ('骑龙回马', '기룡회마(Dragon Return)'),
    ('大风车', '대풍차(Windmill)'),
    ('纵地', '종지(Ground)'),
    ('龙卷风', '용권풍(Tornado)'),
    ('风墙', '풍벽(Wind Wall)'),
    ('易武', '역무(Weapon Swap)'),
    ('跳劈', '점벽(Jump Slash)'),
    ('滑铲', '활삽(Slide)'),
    ('响指', '탄지(Snap)'),
    ('怒斩马', '노참마(Fury Slash)'),
    ('扫千军', '소천군(Sweep Army)'),
    ('飞鸿踏雪', '비홍답설(Flying Snow)'),
    ('白刃杀将', '백인살장(Blade Kill)'),
    ('泥犁三垢', '이리삼구(Mud Triple)'),
    ('如来金刚印', '여래금강인(Buddha Seal)'),
    ('三段跳如来', '3단점프 여래(Triple Jump Buddha)'),
    ('共鸣', '공명(Resonance)'),
    ('处决', '처결(Execute)'),
    ('连击', '연격(Combo)'),
    ('吸血', '흡혈(Lifesteal)'),
    ('回血', '회복(Heal)'),
    ('免死', '면사(Death Immunity)'),
    ('破防', '파방(Armor Break)'),
    ('回耐', '내력회복(Stamina Regen)'),
    ('回气', '기력회복(Chi Regen)'),
    # ===== 장비 부위 =====
    ('部位', '부위(Part)'),
    ('冠胄', '관주(Helm)'),
    ('胸甲', '흉갑(Chest)'),
    ('胫甲', '경갑(Greave)'),
    ('腕甲', '완갑(Bracer)'),
    ('环', '고리(Ring)'),
    ('珮', '패옥(Jade)'),
    # ===== 기타 =====
    ('气血', '기혈(HP)'),
    ('血', '혈(HP)'),
    ('说明', '설명(Description)'),
    ('赞助名单', '후원명단(Sponsors)'),
    ('更新', '업데이트(Update)'),
    ('升级消耗', '레벨업 소모(Upgrade Cost)'),
    ('升级', '레벨업(Upgrade)'),
    ('累计', '누적(Total)'),
    ('等级', '레벨(Level)'),
    ('级', '레벨(Lv)'),
    ('攻击', '공격(ATK)'),
    ('是', '예(Yes)'),
    ('否', '아니오(No)'),
    ('无', '없음(None)'),
    ('弓', '궁(Bow)'),
    ('杂', '기타(Misc)'),
    ('刺', '자(Thrust)'),
    ('隐藏', '숨겨진(Hidden)'),
    ('弃坑，停更了', '접음, 업데이트 종료'),
    ('该品阶为固定值', '해당 등급은 고정값'),
    ('面板属性来源', '패널속성 출처(Panel Stat Source)'),
    ('心法升级消耗', '심법레벨업소모(Mind Method Upgrade Cost)'),
    ('武学隐藏属性', '무학숨겨진속성(Hidden Martial Stat)'),
    ('武学隐藏本系属攻', '무학숨겨진본계속공(Hidden Main Attri ATK)'),
    ('奇术倍率', '기술배율(Mystic Ratio)'),
    ('怪物防御', '몬스터방어(Monster DEF)'),
    ('赛季天赋', '시즌천부(Season Talent)'),
    ('加速', '가속(Speed Up)'),
    ('攻速', '공속(ATK Speed)'),
    ('直伤', '직접피해(Direct DMG)'),
    ('减防', '감방(DEF Reduce)'),
    ('减外抗', '외저감소(Phys Resist Reduce)'),
    ('动画', '애니메이션(Animation)'),
    ('前摇', '선딜(Pre-Cast)'),
    ('后摇', '후딜(After-Cast)'),
    ('触发', '발동(Trigger)'),
    ('概率', '확률(Probability)'),
    ('层数', '중첩(Stacks)'),
    ('层', '중(Stack)'),
    ('秒', '초(sec)'),
    ('段', '단(hit)'),
    ('发', '발(hit)'),
    ('领先度', '선행도(Lead)'),
    ('各系统', '각 시스템(Systems)'),
    ('叠音', '중음(Overtone)'),
    ('蹊跷', '기교(Trick)'),
    ('基础双会', '기본쌍회(Basic Dual Crit)'),
    ('1分钟桩', '1분DPS측정(1min DPS Test)'),
    ('白字面板', '백자패널(White Text Panel)'),
    # ===== 추가 미번역 용어 =====
    # 일반 단어
    ('提升', '향상(Boost)'),
    ('最小', '최소(Min)'),
    ('最大', '최대(Max)'),
    ('和', '와(and)'),
    ('各', '각(Each)'),
    ('下', '하(Lower)'),
    ('上', '상(Upper)'),
    ('没有', '없음(None)'),
    ('没', '없음(No)'),
    ('有', '있음(Has)'),
    ('第', '제(No.)'),
    ('收尾', '마무리(Finish)'),
    ('进', '진입(Enter)'),
    ('打满', '풀딜(Full Hit)'),
    ('吃满', '풀적용(Full Apply)'),
    ('左右', '정도(Approx)'),
    ('大概', '대략(Approx)'),
    ('大致', '대략(Approx)'),
    ('实际', '실제(Actual)'),
    ('计算', '계산(Calc)'),
    ('期望', '기대치(Expected)'),
    ('对比', '비교(Compare)'),
    ('不包括', '미포함(Exclude)'),
    ('包括', '포함(Include)'),
    ('总伤', '총피해(Total DMG)'),
    ('自带', '내장(Built-in)'),
    ('等效', '동등(Equivalent)'),
    ('品阶', '등급(Grade)'),
    ('数值', '수치(Value)'),
    ('对应', '대응(Correspond)'),
    ('关系', '관계(Relation)'),
    ('一览表', '일람표(List)'),
    ('注：', '주：(Note:)'),
    ('注意', '주의(Caution)'),
    # 전투관련 추가
    ('战意', '전의(Battle Spirit)'),
    ('蛤蟆', '두꺼비(Toad)'),
    ('毒', '독(Poison)'),
    ('初级', '초급(Basic)'),
    ('次级', '차급(Secondary)'),
    ('蟾毒', '섬독(Toad Poison)'),
    ('地震', '지진(Earthquake)'),
    ('撞', '충돌(Crash)'),
    ('灼烧', '작열(Burn)'),
    ('火', '화(Fire)'),
    ('酒气爆炸', '주기폭발(Alcohol Explosion)'),
    ('药叉', '약차(Yaksha)'),
    ('猴戏', '후극(Monkey Play)'),
    ('剑气', '검기(Sword Chi)'),
    ('枪Q', '창Q(Spear Q)'),
    ('剑Q', '검Q(Sword Q)'),
    ('伞Q', '산Q(Umbrella Q)'),
    ('鼠Q', '쥐Q(Rat Q)'),
    ('扇Q', '부채Q(Fan Q)'),
    ('丢刀', '칼던지기(Throw Blade)'),
    ('丢伞', '산던지기(Throw Umbrella)'),
    ('回伞', '산회수(Return Umbrella)'),
    ('吃', '적용(Apply)'),
    ('叠加', '중첩(Stack)'),
    ('叠', '중첩(Stack)'),
    ('结算', '정산(Settle)'),
    ('效果', '효과(Effect)'),
    ('控', '컨트롤(Control)'),
    ('解控', '해제(Break Free)'),
    ('闪避', '회피(Dodge)'),
    ('闪', '회피(Dodge)'),
    ('残影', '잔영(Afterimage)'),
    ('黄字', '황자(Yellow Text)'),
    ('则', '이면(then)'),
    ('挂', '걸기(Apply)'),
    ('自己', '자신(Self)'),
    ('队友', '팀원(Teammate)'),
    ('标记', '마킹(Mark)'),
    ('不影响', '영향없음(No Effect)'),
    ('跟', '동일(Same as)'),
    ('一个', '하나의(one)'),
    ('不', '않음(Not)'),
    ('能', '가능(Can)'),
    ('可以', '가능(Can)'),
    ('只', '만(Only)'),
    ('都', '모두(All)'),
    ('也', '또한(Also)'),
    ('要', '필요(Need)'),
    ('比', '비교(vs)'),
    ('好', '좋음(Good)'),
    ('多', '더(More)'),
    ('少', '적은(Less)'),
    ('满', '만(Full)'),
    ('空', '빈(Empty)'),
    # 스킬 관련 추가
    ('尘绳', '진승(Dust Rope)'),
    ('绳标', '승표(Rope Mark)'),
    ('如来', '여래(Buddha)'),
    ('浮空', '부유(Float)'),
    ('气竭前', '기갈전(Pre-Exhaust)'),
    ('气竭后', '기갈후(Post-Exhaust)'),
    ('先判定', '선판정(Pre-Check)'),
    ('命中', '명중(Hit)'),
    ('未', '미(Not)'),
    ('转化', '전환(Convert)'),
    ('率', '률(Rate)'),
    ('伤害', '피해(DMG)'),
    ('百分比', '%(Percent)'),
    ('百', '백(100)'),
    ('万', '만(10000)'),
    # 좀더 구체적인 구문들
    ('纯외공(Phys ATK)，', '순수외공,'),
    ('能吃', '적용됨(Applied)'),
    ('不吃', '미적용(Not Applied)'),
    ('生效', '발동(Active)'),
    ('不生效', '미발동(Inactive)'),
    ('有效', '유효(Valid)'),
    ('无效', '무효(Invalid)'),
    ('上限', '상한(Cap)'),
    ('分界线', '경계선(Threshold)'),
    ('固定', '고정(Fixed)'),
    ('额外', '추가(Extra)'),
    ('送', '제공(Give)'),
    ('立即', '즉시(Instant)'),
    ('持续', '지속(Sustained)'),
    ('瞬间', '순간(Instant)'),
    ('间隔', '간격(Interval)'),
    ('整套', '전체세트(Full Set)'),
    ('单独', '단독(Solo)'),
    ('同时', '동시(Simultaneous)'),
    ('存在', '존재(Exist)'),
    ('消耗', '소모(Cost)'),
    ('恢复', '회복(Recover)'),
    ('开始', '시작(Start)'),
    ('停止', '정지(Stop)'),
    ('之后', '이후(After)'),
    ('之前', '이전(Before)'),
    ('以前', '이전(Before)'),
    ('以后', '이후(After)'),
    ('现在', '현재(Now)'),
    ('出伤', '피해발생(Deal DMG)'),
    ('测试', '테스트(Test)'),
    ('测算', '계산(Calculate)'),
    ('模拟', '시뮬레이션(Simulate)'),
    ('竞速', '타임어택(Speed Run)'),
    ('后台', '백그라운드(Background)'),
    ('奶量', '힐량(Heal Amount)'),
    ('奶增', '힐증(Heal Boost)'),
    ('奶', '힐(Heal)'),
    ('养成', '육성(Build)'),
    ('毕业', '졸업(Graduation)'),
    ('配置', '세팅(Setup)'),
    ('右边', '오른쪽(Right)'),
    ('左边', '왼쪽(Left)'),
    ('上边', '위쪽(Top)'),
    ('下面', '아래쪽(Bottom)'),
    ('两件', '2개(2 pieces)'),
    ('函数', '함수(Function)'),
    ('特殊', '특수(Special)'),
    ('处理', '처리(Process)'),
    ('乘', '곱(Multiply)'),
    ('两个', '2개(Two)'),
    ('循环', '순환(Cycle)'),
    ('加速Q', '가속Q(Speed Q)'),
    ('连', '연속(Chain)'),
    ('砍满', '풀타(Full Slash)'),
    ('无缝', '끊김없이(Seamless)'),
    ('自动', '자동(Auto)'),
    ('手动', '수동(Manual)'),
    ('按', '기준(Based on)'),
    ('算', '계산(Calc)'),
    ('参考', '참고(Reference)'),
    ('简单', '간단(Simple)'),
    ('高', '높음(High)'),
    ('低', '낮음(Low)'),
    ('如需', '필요시(If needed)'),
    ('复制', '복사(Copy)'),
    ('一页', '1페이지(1 page)'),
    ('填', '입력(Fill)'),
    ('清零', '초기화(Reset)'),
    ('里面', '내부(Inside)'),
    ('各个', '각각(Each)'),
    ('列', '열(Column)'),
    ('表', '표(Table)'),
    ('套', '세트(Set)'),
    ('即', '즉(i.e.)'),
    ('或', '또는(or)'),
    ('与', '와(and)'),
    ('被', '당함(by)'),
    ('把', '을(to)'),
    ('给', '에게(to)'),
    ('做', '하기(do)'),
    ('看', '보기(See)'),
    ('用', '사용(Use)'),
    ('需', '필요(Need)'),
    ('先', '먼저(First)'),
    ('后', '후(After)'),
    ('前', '전(Before)'),
    ('中', '중(During)'),
    ('外', '외(Outer)'),
    ('内', '내(Inner)'),
    ('拟合', '피팅(Fitting)'),
    ('刀势', '도세(Blade Stance)'),
    ('区间', '구간(Range)'),
    ('像素', '픽셀(Pixel)'),
    ('实际值', '실제값(Actual)'),
    ('计算值', '계산값(Calc)'),
    ('玩家', '플레이어(Player)'),
    ('单人', '솔로(Solo)'),
    ('多人', '멀티(Multi)'),
    ('镇守', '수호(Guard)'),
    ('距离', '거리(Distance)'),
    ('米', '미터(m)'),
    ('贴脸', '근접(Close Range)'),
    # 장비/아이템 추가
    ('武库', '무고(Arsenal)'),
    ('叠飞', '겹비행(Stack Fly)'),
    ('蓝', '파랑(Blue)'),
    ('紫', '보라(Purple)'),
    ('金', '금(Gold)'),
    ('绿', '초록(Green)'),
    ('金色', '금색(Gold)'),
    ('紫色', '보라색(Purple)'),
    ('蓝色', '파란색(Blue)'),
    ('绿色', '초록색(Green)'),
    ('满值', '만값(Max Value)'),
    ('日志', '로그(Log)'),
    ('赞助', '후원(Sponsor)'),
    ('感谢', '감사(Thanks)'),
    ('群友', '그룹원(Group Member)'),
    ('帮忙', '도움(Help)'),
    ('原贴', '원글(Original Post)'),
    ('常见', '일반적(Common)'),
    ('历史', '역사(History)'),
    ('优先', '우선(Priority)'),
    ('收益', '수익(Benefit)'),
    ('神秘', '신비(Mysterious)'),
    ('保守', '보수적(Conservative)'),
    ('一点', '조금(A bit)'),
    ('废弃', '폐기(Deprecated)'),
    ('钧', '균(Jun)'),
    ('整套', '전체(Full Set)'),
    ('小人', '소인(Minion)'),
    ('秒Q', '즉시Q(Instant Q)'),
    ('慢Q', '느린Q(Slow Q)'),
    ('快', '빠름(Fast)'),
    ('慢', '느림(Slow)'),
    ('完美', '완벽(Perfect)'),
    ('普通', '일반(Normal)'),
    ('游戏', '게임(Game)'),
    ('写', '표기(Write)'),
    ('假', '거짓(Fake)'),
    ('真', '진짜(Real)'),
    ('动作', '동작(Action)'),
    ('总', '총(Total)'),
    ('只有', '오직(Only)'),
    ('当', '시(When)'),
    ('如果', '만약(If)'),
    ('因为', '왜냐하면(Because)'),
    ('所以', '그래서(So)'),
    ('但是', '하지만(But)'),
    ('但', '하지만(But)'),
    ('然后', '그다음(Then)'),
    ('其他', '기타(Other)'),
    ('本', '본(Main)'),
    ('目标', '타겟(Target)'),
    ('添加', '추가(Add)'),
    ('继续', '계속(Continue)'),
    ('触发条件', '발동조건(Trigger Condition)'),
    ('条件', '조건(Condition)'),
    ('相关', '관련(Related)'),
    ('默认', '기본(Default)'),
    ('出现', '발생(Appear)'),
    ('以下', '이하(Below)'),
    ('以上', '이상(Above)'),
    ('新', '새(New)'),
    ('旧', '구(Old)'),
    ('更', '더(More)'),
    ('小', '소(Small)'),
    ('大', '대(Large)'),
    ('一', '일(1)'),
    ('二', '이(2)'),
    ('三', '삼(3)'),
    ('四', '사(4)'),
    ('五', '오(5)'),
    ('六', '육(6)'),
    ('七', '칠(7)'),
    ('八', '팔(8)'),
    ('九', '구(9)'),
    ('十', '십(10)'),
    ('百', '백(100)'),
]

# 정렬: 긴 원문부터 먼저 매칭
TERM_DICT = sorted(TERM_DICT_RAW, key=lambda x: len(x[0]), reverse=True)

# ============================================================
# 번역 함수
# ============================================================
def translate_text(text, idx=None):
    """공유 문자열 번역"""
    if not text or not text.strip():
        return text
    # 숫자만 있으면 스킵
    if re.match(r'^[\d\.\-\+\%\s\,]+$', text):
        return text
    # URL 스킵
    if text.startswith('http'):
        return text
    # 후원자 닉네임 (*로 시작) 스킵
    if text.startswith('*') or re.match(r'^[A-Z]\*[a-z]$', text):
        return text
    
    result = text
    for src, tgt in TERM_DICT:
        if src in result:
            result = result.replace(src, tgt)
    return result

# ============================================================
# XML 처리
# ============================================================
NS = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'

def process_shared_strings(xml_data):
    """sharedStrings.xml의 텍스트 번역"""
    # 네임스페이스 등록 (직렬화시 ns0: 방지)
    ET.register_namespace('', NS)
    # 기타 네임스페이스도 보존
    for ns_uri in ['http://schemas.openxmlformats.org/markup-compatibility/2006',
                    'http://schemas.microsoft.com/office/spreadsheetml/2009/9/main']:
        prefix = 'mc' if 'compatibility' in ns_uri else 'x14ac'
        try:
            ET.register_namespace(prefix, ns_uri)
        except:
            pass
    
    root = ET.fromstring(xml_data)
    ns = {'s': NS}
    
    translated_count = 0
    for idx, si in enumerate(root.findall('s:si', ns)):
        # 모든 <t> 텍스트 수집
        texts = []
        for t_elem in si.iter(f'{{{NS}}}t'):
            if t_elem.text:
                texts.append(t_elem.text)
        original = ''.join(texts)
        translated = translate_text(original, idx)
        
        if translated != original:
            translated_count += 1
            # 자식 요소 모두 제거 후 단일 <t>로 대체
            for child in list(si):
                si.remove(child)
            t_new = ET.SubElement(si, f'{{{NS}}}t')
            t_new.text = translated
            if translated and (translated[0] == ' ' or translated[-1] == ' '):
                t_new.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
    
    print(f"  번역된 문자열: {translated_count}/{idx+1}개")
    return ET.tostring(root, encoding='UTF-8', xml_declaration=True)

def process_workbook(xml_data):
    """workbook.xml의 시트명 변경"""
    xml_str = xml_data.decode('utf-8')
    for old_name, new_name in SHEET_NAME_MAP.items():
        # XML 속성 내에서 & → &amp;
        old_esc = old_name.replace('&', '&amp;')
        new_esc = new_name.replace('&', '&amp;')
        xml_str = xml_str.replace(f'name="{old_esc}"', f'name="{new_esc}"')
    return xml_str.encode('utf-8')

def process_worksheet(xml_data):
    """워크시트의 수식 내 시트명 참조 업데이트"""
    xml_str = xml_data.decode('utf-8')
    for old_name, new_name in SHEET_NAME_MAP.items():
        # 따옴표로 감싼 참조: 'Sheet Name'!
        xml_str = xml_str.replace(f"'{old_name}'!", f"'{new_name}'!")
        # 따옴표 없는 참조: SheetName!
        xml_str = xml_str.replace(f"{old_name}!", f"{new_name}!")
        # XML 이스케이프된 &amp; 처리
        old_esc = old_name.replace('&', '&amp;')
        if old_esc != old_name:
            new_esc = new_name.replace('&', '&amp;')
            xml_str = xml_str.replace(f"'{old_esc}'!", f"'{new_esc}'!")
            xml_str = xml_str.replace(f"{old_esc}!", f"{new_esc}!")
    return xml_str.encode('utf-8')

# ============================================================
# 메인 실행
# ============================================================
def main():
    print(f"원본: {SOURCE}")
    print(f"출력: {OUTPUT}")
    
    if not os.path.exists(SOURCE):
        print("오류: 원본 파일을 찾을 수 없습니다!")
        return
    
    print("\n번역 시작...")
    with zipfile.ZipFile(SOURCE, 'r') as zin:
        with zipfile.ZipFile(OUTPUT, 'w', zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)
                
                if item.filename == 'xl/sharedStrings.xml':
                    print(f"\n[1/3] 공유 문자열 번역 중...")
                    data = process_shared_strings(data)
                elif item.filename == 'xl/workbook.xml':
                    print(f"[2/3] 시트명 번역 중...")
                    data = process_workbook(data)
                elif item.filename.startswith('xl/worksheets/sheet'):
                    sheet_num = item.filename.split('sheet')[1].split('.')[0]
                    print(f"[3/3] 시트{sheet_num} 수식 업데이트 중...")
                    data = process_worksheet(data)
                
                zout.writestr(item, data)
    
    file_size = os.path.getsize(OUTPUT)
    print(f"\n✅ 번역 완료!")
    print(f"   파일: {OUTPUT}")
    print(f"   크기: {file_size:,} bytes")

if __name__ == '__main__':
    main()
